config/routes.rb
Fmf2::Application.routes.draw do

  resources :orders

  resources :inventories

  resources :restaurants

  resources :chefs

root :to => "Farms#index"

get "/produces/type/:category" => "Produces#showtype", :as => "protype"

  resources :produces

  resources :farms

  resources :farmers

end

app/models/farm.rb
class Farm < ActiveRecord::Base
  attr_accessible :address, :zip, :farmer_id

  belongs_to :farmer
  has_many :produces

  validates_associated :produces
  validates :address, :length => { :minimum => 2 },
   					  :uniqueness => { :case_sensitive => false }
end




#INVENTORY TO LINK FARM AND PRODUCES?

#FARM HAS_MANY INVENTORY
#PRODUCE HAS_MANY INVENTORY



# from campfire:
#you just need to make sure to use Produce.find(123).
						#include(:farm).include(:farmer)

app/controllers/farms_controller.rb
class FarmsController < ApplicationController
  # GET /farms
  # GET /farms.json
  def index
    @farms = Farm.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @farms }
    end
  end

  # GET /farms/1
  # GET /farms/1.json
  def show
    @farm = Farm.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @farm }
    end
  end

  # GET /farms/new
  # GET /farms/new.json
  def new
    @farm = Farm.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @farm }
    end
  end

  # GET /farms/1/edit
  def edit
    @farm = Farm.find(params[:id])
  end

  # POST /farms
  # POST /farms.json
  def create
    @farm = Farm.new(params[:farm])
    (@farm.lat, @farm.lon) = view_context.getcoordf(@farm.zip)

    respond_to do |format|
      if @farm.save
        format.html { redirect_to @farm, notice: 'Farm was successfully created.' }
        format.json { render json: @farm, status: :created, location: @farm }
      else
        format.html { render action: "new" }
        format.json { render json: @farm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /farms/1
  # PUT /farms/1.json
  def update
    @farm = Farm.find(params[:id])
    (@farm.lat, @farm.lon) = view_context.getcoordf(@farm.zip)

    respond_to do |format|
      if @farm.update_attributes(params[:farm])
        format.html { redirect_to @farm, notice: 'Farm was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @farm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /farms/1
  # DELETE /farms/1.json
  def destroy
    @farm = Farm.find(params[:id])
    @farm.destroy

    respond_to do |format|
      format.html { redirect_to farms_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/farms_helper.rb
module FarmsHelper

def getcoordf(zip)
  url = "http://maps.googleapis.com/maps/api/geocode/json?address=#{zip}&sensor=false"
  response = open(url).read
  json_response = JSON.parse(response)
  lat = json_response["results"].first["geometry"]["location"]["lat"]
  lng = json_response["results"].first["geometry"]["location"]["lng"]
	return [lat,lng]
end


end



 #  url = "http://maps.googleapis.com/maps/api/geocode/json?address=60601&sensor=false"
 #  response = open(url).read
 #  json_response = JSON.parse(response)
 #  lat = json_response["results"].first["geometry"]["location"]["lat"]
 #  lng = json_response["results"].first["geometry"]["location"]["lng"]
 # (z,x) = [lat,lng]

app/views/farms/_form.html.erb
<%= form_for(@farm) do |f| %>
  <% if @farm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@farm.errors.count, "error") %> prohibited this farm from being saved:</h2>

      <ul>
      <% @farm.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
 
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  
  <div class="field">
    <%= f.collection_select(:farmer_id, Farmer.all, :id, :name) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/farms/edit.html.erb
<h1>Editing farm</h1>

<%= render 'form' %>

<%= link_to 'Show', @farm %> |
<%= link_to 'Back', farms_path %>

app/views/farms/index.html.erb
<h1>Listing farms</h1>

<table>
  <tr>
    <th>Address</th>
    <th>Zip</th>
    <th>Farmer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @farms.each do |farm| %>
  <tr>
    <td><%= farm.address %></td>
    <td><%= farm.zip %></td>
    <td><%= farm.farmer %></td>
    <td><%= link_to 'Show', farm %></td>
    <td><%= link_to 'Edit', edit_farm_path(farm) %></td>
    <td><%= link_to 'Destroy', farm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Farm', new_farm_path %> |
<%= link_to 'Farmers', farmers_path %> |
<%= link_to 'Produce', produces_path %>

app/views/farms/new.html.erb
<h1>New farm</h1>

<%= render 'form' %>

<%= link_to 'Back', farms_path %>

app/views/farms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Address:</b>
  <%= @farm.address %>
</p>

<p>
  <b>Zip:</b>
  <%= @farm.zip %>
</p>

<b>Income:</b>
  <%= number_to_currency(@farm.income) %>
</p>

<p>
  <b>Farmer:</b>
  <%= @farm.farmer.name %>
</p>

<table>
  <tr>
    <th>Produce Type</th>
    <th>Produce</th>
    <th>Qty</th>
    <th>Produce</th>  
    <th> / </th>
    <th>Cost</th>
    <th></th>
  </tr>

<% @farm.produces.each do |produce| %>
  <tr>
    <td><%= produce.category %></td>
	<td><%= produce.name %></td>
    <td><%= produce.amount %></td>
    <td><%= produce.bundle %></td>
    <td><%= number_to_currency(produce.cost) %> /<%= produce.bundle %></td>
  </tr>
<% end %>
</table>





<%= link_to 'Edit', edit_farm_path(@farm) %> |
<%= link_to 'Back', farms_path %>