config/routes.rb
Fmf2::Application.routes.draw do

  resources :orders

  resources :inventories

  resources :restaurants

  resources :chefs

root :to => "Farms#index"

get "/produces/type/:category" => "Produces#showtype", :as => "protype"

  resources :produces

  resources :farms

  resources :farmers

end

app/models/chef.rb
class Chef < ActiveRecord::Base
  attr_accessible :name

  has_many :restaurants
  has_many :orders, :through => :restaurants

  validates_associated :restaurants
  validates_associated :orders
  validates :name, :length => { :minimum => 2 }, 
  				   :uniqueness => { :case_sensitive => false }
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  # GET /chefs
  # GET /chefs.json
  def index
    @chefs = Chef.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @chefs }
    end
  end

  # GET /chefs/1
  # GET /chefs/1.json
  def show
    @chef = Chef.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @chef }
    end
  end

  # GET /chefs/new
  # GET /chefs/new.json
  def new
    @chef = Chef.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @chef }
    end
  end

  # GET /chefs/1/edit
  def edit
    @chef = Chef.find(params[:id])
  end

  # POST /chefs
  # POST /chefs.json
  def create
    @chef = Chef.new(params[:chef])

    respond_to do |format|
      if @chef.save
        format.html { redirect_to @chef, notice: 'Chef was successfully created.' }
        format.json { render json: @chef, status: :created, location: @chef }
      else
        format.html { render action: "new" }
        format.json { render json: @chef.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /chefs/1
  # PUT /chefs/1.json
  def update
    @chef = Chef.find(params[:id])

    respond_to do |format|
      if @chef.update_attributes(params[:chef])
        format.html { redirect_to @chef, notice: 'Chef was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @chef.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chefs/1
  # DELETE /chefs/1.json
  def destroy
    @chef = Chef.find(params[:id])
    @chef.destroy

    respond_to do |format|
      format.html { redirect_to chefs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/chefs_helper.rb
module ChefsHelper
end

app/views/chefs/_form.html.erb
<%= form_for(@chef) do |f| %>
  <% if @chef.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chef.errors.count, "error") %> prohibited this chef from being saved:</h2>

      <ul>
      <% @chef.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chefs/edit.html.erb
<h1>Editing chef</h1>

<%= render 'form' %>

<%= link_to 'Show', @chef %> |
<%= link_to 'Back', chefs_path %>

app/views/chefs/index.html.erb
<h1>Listing chefs</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @chefs.each do |chef| %>
  <tr>
    <td><%= chef.name %></td>
    <td><%= link_to 'Show', chef %></td>
    <td><%= link_to 'Edit', edit_chef_path(chef) %></td>
    <td><%= link_to 'Destroy', chef, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Chef', new_chef_path %> |
<%= link_to 'Restaurants', restaurants_path %> |
<%= link_to 'Orders', orders_path %>

app/views/chefs/new.html.erb
<h1>New chef</h1>

<%= render 'form' %>

<%= link_to 'Back', chefs_path %>

app/views/chefs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @chef.name %>
</p>

<%= link_to 'Edit', edit_chef_path(@chef) %> |
<%= link_to 'Back', chefs_path %>