config/routes.rb
Fmf2::Application.routes.draw do

  resources :orders

  resources :inventories

  resources :restaurants

  resources :chefs

root :to => "Farms#index"

get "/produces/type/:category" => "Produces#showtype", :as => "protype"

  resources :produces

  resources :farms

  resources :farmers

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  attr_accessible :address, :zip, :chef_id#, :bill

  belongs_to :chef
  has_many :orders

  validates_associated :orders
  validates :address, :length => { :minimum => 2 },
  					  :uniqueness => { :case_sensitive => false }
  #validates :bill, :numericality => true
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @restaurants }
    end
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @restaurant = Restaurant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @restaurant }
    end
  end

  # GET /restaurants/new
  # GET /restaurants/new.json
  def new
    @restaurant = Restaurant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @restaurant }
    end
  end

  # GET /restaurants/1/edit
  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(params[:restaurant])
    (@restaurant.lat, @restaurant.lon) = view_context.getcoordr(@restaurant.zip)


    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render json: @restaurant, status: :created, location: @restaurant }
      else
        format.html { render action: "new" }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /restaurants/1
  # PUT /restaurants/1.json
  def update
    @restaurant = Restaurant.find(params[:id])
    (@restaurant.lat, @restaurant.lon) = view_context.getcoordr(@restaurant.zip)

    respond_to do |format|
      if @restaurant.update_attributes(params[:restaurant])
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    respond_to do |format|
      format.html { redirect_to restaurants_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper

def getcoordr(zip)
  url = "http://maps.googleapis.com/maps/api/geocode/json?address=#{zip}&sensor=false"
  response = open(url).read
  json_response = JSON.parse(response)
  lat = json_response["results"].first["geometry"]["location"]["lat"]
  lng = json_response["results"].first["geometry"]["location"]["lng"]
	return [lat,lng]
end


end

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>

  <div class="field">
    <%= f.collection_select(:chef_id, Chef.all, :id, :name) %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Listing restaurants</h1>

<table>
  <tr>
    <th>Address</th>
    <th>Zip</th>
    <th>Chef</th>
    <th>Bill</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @restaurants.each do |restaurant| %>
  <tr>
    <td><%= restaurant.address %></td>
    <td><%= restaurant.zip %></td>
    <td><%= restaurant.chef.name %></td>
    <td>$<%= restaurant.bill %></td>
    <td><%= link_to 'Show', restaurant %></td>
    <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
    <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Restaurant', new_restaurant_path %> |
<%= link_to 'Chefs', chefs_path %> |
<%= link_to 'Orders', orders_path %>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Address:</b>
  <%= @restaurant.address %>
</p>

<p>
  <b>Zip:</b>
  <%= @restaurant.zip %>
</p>

<p>
  <b>Bill:</b>
  $<%= @restaurant.bill %>
</p>


<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>