config/routes.rb
Fmf2::Application.routes.draw do

  resources :orders

  resources :inventories

  resources :restaurants

  resources :chefs

root :to => "Farms#index"

get "/produces/type/:category" => "Produces#showtype", :as => "protype"

  resources :produces

  resources :farms

  resources :farmers

end

app/models/produce.rb
class Produce < ActiveRecord::Base
  attr_accessible :amount, :bundle, :category, :cost, :name, :farm_id

  belongs_to :farm
  has_many :orders, :through => :order_items

  validates :amount, :numericality => { :only_integer => true,
  									 	:greater_than_or_equal_to => 0 }
  validates :bundle, :inclusion => { :in => %w(ea bushel lb),
    	:message => "%{value} is not a valid group" }
  validates :category, :inclusion => { :in => %w(fruits vegetables livestock pumpkins),
    	:message => "%{value} is not a valid category" }
  validates :cost, :numericality => { :greater_than => 0 }
  validates :name, :length => { :minimum => 2 }

 def farmername
   return farm.farmer.name
 end

end

app/controllers/produces_controller.rb
class ProducesController < ApplicationController
  # GET /produces
  # GET /produces.json

  def index
   # @produces = Produce.all
    @search = Produce.search(params[:q])
    @produces = @search.result

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @produces }
    end
  end

 def showtype
    @produces = Produce.find_all_by_category(params[:category])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @produces }
    end
  end

  # GET /produces/1
  # GET /produces/1.json
  def show
    @produce = Produce.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @produce }
    end
  end

  # GET /produces/new
  # GET /produces/new.json
  def new
    @produce = Produce.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @produce }
    end
  end

  # GET /produces/1/edit
  def edit
    @produce = Produce.find(params[:id])
  end

  # POST /produces
  # POST /produces.json
  def create
    @produce = Produce.new(params[:produce])

    respond_to do |format|
      if @produce.save
        format.html { redirect_to @produce, notice: 'Produce was successfully created.' }
        format.json { render json: @produce, status: :created, location: @produce }
      else
        format.html { render action: "new" }
        format.json { render json: @produce.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /produces/1
  # PUT /produces/1.json
  def update
    @produce = Produce.find(params[:id])

    respond_to do |format|
      if @produce.update_attributes(params[:produce])
        format.html { redirect_to @produce, notice: 'Produce was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @produce.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produces/1
  # DELETE /produces/1.json
  def destroy
    @produce = Produce.find(params[:id])
    @produce.destroy

    respond_to do |format|
      format.html { redirect_to produces_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/produces_helper.rb
module ProducesHelper
end

app/views/produces/_form.html.erb
<%= form_for(@produce) do |f| %>
  <% if @produce.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produce.errors.count, "error") %> prohibited this produce from being saved:</h2>

      <ul>
      <% @produce.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br>
  Category
  <div>
    <select name="produce[category]">
        <option value="fruits">fruits</option>
        <option value="vegetables">vegetables</option>
        <option value="livestock">livestock</option>
        <option value="pumpkins">pumpkins</option>  
    </select>
  </div>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.number_field :amount %>

    , <%= f.label :cost %> $<%= f.text_field :cost %>

    <select name="produce[bundle]">
        <option value="ea">ea</option>
        <option value="lb">lb</option>
        <option value="bushel">bushel</option>
    </select>
  </div>
  Farm
  <div class="field">
    <%= f.collection_select :farm_id, Farm.all, :id, :address %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/produces/edit.html.erb
<h1>Editing produce</h1>

<%= render 'form' %>

<%= link_to 'Show', @produce %> |
<%= link_to 'Back', produces_path %>

app/views/produces/index.html.erb
<h1>Listing produces</h1>

<%= search_form_for @search do |f| %>
    <div class="field">
        <%= f.label :name_cont, "Name?" %>
        <%= f.text_field :name_cont %>
    </div>
    <div class="field">
        <%= f.label :amount_lteq, "Distance <" %>
        <%= f.text_field :amount_lteq %>
    </div>
    <div class="actions"><%= f.submit "Search" %>
    </div>
<% end %>

<br><br><br>

<table>
  <tr>
    <th>Name</th>
    <th>Amount</th>
    <th>Cost</th>
    <th>Bundle</th>
    <th>Category</th>
    <th>Farm</th>
    <th>Farm</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @produces.each do |produce| %>
  <tr>
    <td><%= produce.name %></td>
    <td><%= produce.amount %></td>
    <td><%= number_to_currency(produce.cost) %></td>
    <td>/<%= produce.bundle %></td>
    <td><%= link_to "#{produce.category}", protype_path(produce.category) %></td>
    <td><%= produce.farm.address %></td>
    <td><%= produce.farm %></td>
    <td><%= link_to 'Show', produce %></td>
    <td><%= link_to 'Edit', edit_produce_path(produce) %></td>
    <td><%= link_to 'Destroy', produce, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Produce', new_produce_path %> |
<%= link_to 'Farmers', farmers_path %> |
<%= link_to 'Farms', farms_path %>

app/views/produces/new.html.erb
<h1>New produce</h1>

<%= render 'form' %>

<%= link_to 'Back', produces_path %>

app/views/produces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @produce.name %>
</p>

<p>
  <b>Amount:</b>
  <%= @produce.amount %>
</p>

<p>
  <b>Cost:</b>
  <%= number_to_currency(@produce.cost) %>
</p>

<p>
  <b>Bundle:</b>
  <%= @produce.bundle %>
</p>

<p>
  <b>Category:</b>
  <%= @produce.category %>
</p>

<p>
  <b>Farm:</b>
  <%= @produce.farm.address %>
</p>


<%= link_to 'Edit', edit_produce_path(@produce) %> |
<%= link_to 'Back', produces_path %>






<%= form_for(@produce) do |f| %>
  <% if @produce.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produce.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @produce.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cost %><br />
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/produces/showtype.html.erb
<h1>Listing produces</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Amount</th>
    <th>Cost</th>
    <th>Bundle</th>
    <th>Category</th>
    <th>Farm</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @produces.each do |produce| %>
  <tr>
    <td><%= produce.name %></td>
    <td><%= produce.amount %></td>
    <td><%= number_to_currency(produce.cost) %></td>
    <td>/<%= produce.bundle %></td>
    <td><%= produce.category %></td>
    <td><%= produce.farm.address %></td>
    <td><%= produce.farmername %></td>
    <td><%= link_to 'Show', produce %></td>
    <td><%= link_to 'Edit', edit_produce_path(produce) %></td>
    <td><%= link_to 'Destroy', produce, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Produce', new_produce_path %> |
<%= link_to 'Farmers', farmers_path %> |
<%= link_to 'Farms', farms_path %>